"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
exports.JsxReadmeBadge = void 0;
/* @jsx MD */
var jsx_md_1 = __importDefault(require("jsx-md"));
var Badge_1 = require("../Badge");
/** Display a badge showing that the readme file is autogenerated with jsx-readme */
exports.JsxReadmeBadge = function () { return (jsx_md_1["default"](Badge_1.Badge, { link: "https://dbartholomae.github.io/jsx-readme", imageSource: "https://img.shields.io/badge/jsx--readme-lightgrey" }, "jsx-readme")); };
